-- 사용자 알림.
create table notification (
    id           bigint generated by default as identity primary key,
    recipient_id bigint      not null references member (id),
    type         varchar(40) not null,
    message      text        not null,
    related_id   bigint,
    is_read      boolean     not null,
    created_at   timestamptz not null,
    updated_at   timestamptz not null
);

create index idx_notification_recipient on notification (recipient_id, is_read);
