-- 동행 1건당 채팅방 1개. 동행 삭제 시 함께 삭제.
create table chat_room (
    id           bigint generated by default as identity primary key,
    companion_id bigint      not null unique references companion (id) on delete cascade,
    created_at   timestamptz not null,
    updated_at   timestamptz not null
);
