-- 채팅방 참여자. 방 삭제 시 함께 삭제, 동일 방 내 중복 참여 금지.
create table chat_room_member (
    id         bigint generated by default as identity primary key,
    room_id    bigint      not null references chat_room (id) on delete cascade,
    member_id  bigint      not null references member (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_chat_room_member unique (room_id, member_id)
);

create index idx_chat_room_member_member on chat_room_member (member_id);
