-- 채팅 메시지. 방 삭제 시 함께 삭제.
create table chat_message (
    id         bigint generated by default as identity primary key,
    room_id    bigint      not null references chat_room (id) on delete cascade,
    sender_id  bigint      not null references member (id),
    content    text        not null,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create index idx_chat_message_room on chat_message (room_id, id);
