-- 회원 테이블. 컬럼명은 Spring 기본 물리 네이밍(camelCase -> snake_case)과 일치한다.
-- ddl-auto=validate 이므로 Member 엔티티 매핑과 반드시 일치해야 한다.
create table member (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    password_hash varchar(255),
    nickname      varchar(50)  not null,
    role          varchar(20)  not null,
    provider      varchar(20)  not null,
    provider_id   varchar(255),
    created_at    timestamptz  not null,
    updated_at    timestamptz  not null
);

-- 소셜 로그인 조회(provider + provider_id) 대비 인덱스
create index idx_member_provider on member (provider, provider_id);
