-- 여행 일정 테이블. 컬럼명은 Spring 기본 물리 네이밍과 일치, ddl-auto=validate 대응.
create table trip (
    id          bigint generated by default as identity primary key,
    owner_id    bigint       not null references member (id),
    title       varchar(100) not null,
    destination varchar(100) not null,
    start_date  date         not null,
    end_date    date         not null,
    budget      bigint,
    visibility  varchar(20)  not null,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null
);

create index idx_trip_owner on trip (owner_id);
