-- 여행 일정 내 방문 장소. 여행 삭제 시 함께 삭제(on delete cascade).
create table trip_item (
    id             bigint generated by default as identity primary key,
    trip_id        bigint       not null references trip (id) on delete cascade,
    day_number     integer      not null,
    sort_order     integer      not null,
    place_name     varchar(200) not null,
    memo           text,
    estimated_cost bigint,
    stay_minutes   integer,
    created_at     timestamptz  not null,
    updated_at     timestamptz  not null
);

create index idx_trip_item_trip on trip_item (trip_id, day_number, sort_order);
