-- 동행 모집글. trip_id는 선택적 연결(SET NULL on delete).
create table companion (
    id          bigint generated by default as identity primary key,
    host_id     bigint       not null references member (id),
    trip_id     bigint       references trip (id) on delete set null,
    title       varchar(100) not null,
    content     text,
    destination varchar(100) not null,
    start_date  date         not null,
    end_date    date         not null,
    capacity    integer      not null,
    budget      bigint,
    status      varchar(20)  not null,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null
);

create index idx_companion_status on companion (status);
create index idx_companion_host on companion (host_id);
