-- 동행 지원. 모집글 삭제 시 함께 삭제(cascade). 동일인 중복 지원 금지(unique).
create table companion_application (
    id           bigint generated by default as identity primary key,
    companion_id bigint      not null references companion (id) on delete cascade,
    applicant_id bigint      not null references member (id),
    message      text,
    status       varchar(20) not null,
    created_at   timestamptz not null,
    updated_at   timestamptz not null,
    constraint uq_companion_applicant unique (companion_id, applicant_id)
);

create index idx_application_companion on companion_application (companion_id);
