-- 여행 지출 항목. 여행 삭제 시 함께 삭제.
create table expense (
    id          bigint generated by default as identity primary key,
    trip_id     bigint      not null references trip (id) on delete cascade,
    payer_id    bigint      not null references member (id),
    amount      bigint      not null,
    category    varchar(20) not null,
    description varchar(200),
    spent_on    date        not null,
    created_at  timestamptz not null,
    updated_at  timestamptz not null
);

create index idx_expense_trip on expense (trip_id);
