-- 지출 항목의 참여자별 분담액. 지출/여행 삭제 시 함께 삭제.
create table expense_share (
    id           bigint generated by default as identity primary key,
    expense_id   bigint      not null references expense (id) on delete cascade,
    trip_id      bigint      not null references trip (id) on delete cascade,
    member_id    bigint      not null references member (id),
    share_amount bigint      not null,
    created_at   timestamptz not null,
    updated_at   timestamptz not null
);

create index idx_expense_share_trip on expense_share (trip_id);
create index idx_expense_share_expense on expense_share (expense_id);
